import {MigrationInterface, QueryRunner} from "typeorm";

export class Initial1645683297410 implements MigrationInterface {
    name = 'Initial1645683297410'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_1ba9a6e15c4a588af6233304ab0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_67abb81dc33e75d1743323fd5db"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_47f78f8125ff6110a77cea41aaa"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_fd773efb2eff5ead1948f3dc1f9"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_578f2900539ba65eb5dfbf1e3ad"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_92904cc4ab661f087cbcb60f404"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_8c9b301d18f4ed8cacff33664c6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_214e8e26a3bc13250ef55e9a1af"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "REL_1ba9a6e15c4a588af6233304ab"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "owner_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "about_me"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "REL_67abb81dc33e75d1743323fd5d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "wallet_id"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "last_sale"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "owner_id"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "creator_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "asset_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "buyer_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "seller_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "ownerId" uuid`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "UQ_342cecf691b0d12172e69b2b8f9" UNIQUE ("ownerId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "aboutMe" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birthDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "walletId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_0a95e6aab86ff1b0278c18cf48e" UNIQUE ("walletId")`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "authorId" uuid`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "assetId" uuid`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "imageUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "lastSale" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "ownerId" uuid`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "creatorId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "assetId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "buyerId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "sellerId" uuid`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_342cecf691b0d12172e69b2b8f9" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0a95e6aab86ff1b0278c18cf48e" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4548cc4a409b8651ec75f70e280" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c6b009d2e76dd8d3f45e694d43" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_99cf58fb01a338728806bd5ff25" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_b5f6f034d04b77cae7366ac9dc8" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_7a6e7bd44674390f67b643408b6" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_ec4767e5beacbc7dfaa507d1fc6" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_5848e57fcb8971eeb768c3a6b44" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_5848e57fcb8971eeb768c3a6b44"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_ec4767e5beacbc7dfaa507d1fc6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_7a6e7bd44674390f67b643408b6"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_b5f6f034d04b77cae7366ac9dc8"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_99cf58fb01a338728806bd5ff25"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c6b009d2e76dd8d3f45e694d43"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4548cc4a409b8651ec75f70e280"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0a95e6aab86ff1b0278c18cf48e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_342cecf691b0d12172e69b2b8f9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "creatorId"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "lastSale"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_0a95e6aab86ff1b0278c18cf48e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "aboutMe"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "UQ_342cecf691b0d12172e69b2b8f9"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "seller_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "buyer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "asset_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "creator_id" uuid`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "owner_id" uuid`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "last_sale" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "image_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "asset_id" uuid`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "author_id" uuid`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "wallet_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "REL_67abb81dc33e75d1743323fd5d" UNIQUE ("wallet_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birth_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "about_me" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "owner_id" uuid`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "REL_1ba9a6e15c4a588af6233304ab" UNIQUE ("owner_id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_214e8e26a3bc13250ef55e9a1af" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_8c9b301d18f4ed8cacff33664c6" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_92904cc4ab661f087cbcb60f404" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_578f2900539ba65eb5dfbf1e3ad" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_fd773efb2eff5ead1948f3dc1f9" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_47f78f8125ff6110a77cea41aaa" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_67abb81dc33e75d1743323fd5db" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_1ba9a6e15c4a588af6233304ab0" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
